# Generated by Django 4.2.7 on 2025-08-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_external_id_task_framework_tags_task_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_entries',
            field=models.JSONField(blank=True, default=dict, help_text='Data entries collected for this task'),
        ),
    ]
