# Generated by Django 4.2.7 on 2025-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_data_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_files',
            field=models.IntegerField(default=0, help_text='Number of files expected for this task'),
        ),
    ]
